server:
  servlet:
    context-path: /puppynote

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/puppynote?useSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          exception-handling: ignore
  mail:
    host: smtp.gmail.com
    port: 587
    username: puppynote0330@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

oauth:
  kakao:
    api:
      url: https://kapi.kakao.com
      name: kakaoApi
  google:
    api:
      url: https://www.googleapis.com
      name: googleApi

jwt:
  secret-key: ${JWT_SECRET_KEY}